name: clone-repository

on:
  schedule:
    - cron: '0 * * * *'


jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: sudosubin/git-clone-action@v1
        with:
          repository: 'Leilei332/web-archive'
          platform: 'gitlab'
          path: '/'

    
